### ISSUE TITLE
localparam with operator **

### ISSUE THREAD

**Issue by dramoz** [Nic30/hdlConvertorAst#3]
Hi, I was trying to convert back with ToVerilog2005() and a localparam with operator ** failed.

I think it is a typo at:

`~/anaconda3/envs/jupyter/lib/python3.8/site-packages/hdlConvertorAst-0.4-py3.8.egg/hdlConvertorAst/to/common.py in _precedence_of_expr(self, o)
     85         if not isinstance(o, HdlOp):
     86             return (-1, ASSOCIATIVITY.NONE, None)
---> 87         return self.OP_PRECEDENCE[o.fn] + (o.fn, )
     88 
     89     def visit_HdlOp(self, op):

KeyError: <HdlOpType.POW: 27>`

Let me know if more info or an example is required.
Thanks,
Danilo.

**Comment by Nic30** [comment]
Hello, the issue should be fixed, can you please check if it works for you?

**Comment by dramoz** [comment]
Solved, thanks.
